POST http://localhost:3001/login/
Content-Type: application/json

{
    "firstName": "Manish",
    "email": "manishK@gmail.com", 
    "password": "123456"
}

###
POST http://localhost:3001/register/
Content-Type: application/json

{
    "username": "Amit",
    "firstName": "Amit",
    "lastName": "Gupta",
    "email": "a@gmail.com", 
    "password": "123456",
    "role": "admin"
}

###
POST http://localhost:3001/logout/
content-type: application/json

{
    "username": "Amit",
    "email": "amit@gmail.com",
}

###
POST http://localhost:3001/product/
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbmlzaEtAZ21haWwuY29tIiwidHlwZSI6IlVzZXIiLCJpYXQiOjE2MjYwNzg5MzMsImV4cCI6MTYyNjE2NTMzM30.f1iAaQjr1m2xESyZjW_a4toWyZrJycWgXw7eXTt168o
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text" Laptop
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text" XXL
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="text" 10000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: image/png

< ./1.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--